#!/bin/bash

# 101-manage_my_process script
# Manages the manage_my_process script (start, stop, restart).

PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="/path/to/manage_my_process"

case "$1" in
    start)
        bash $PROCESS_SCRIPT &
        echo $! > $PID_FILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f $PID_FILE ]; then
            kill $(cat $PID_FILE)
            rm -f $PID_FILE
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -f $PID_FILE ]; then
            kill $(cat $PID_FILE)
            rm -f $PID_FILE
        fi
        bash $PROCESS_SCRIPT &
        echo $! > $PID_FILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
